spring:
  application:
    name: turbine
server:
  port: 8989
management:
  server:
    port: 8990
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
turbine:
  app-config: ribbon-consumer # 监控信息的服务名
#  cluster-name-expression: "default"
#  combine-host-port: true
